### ISSUE TITLE
Specify a customer cutpoint using oc_manual=avalue ignored?

### ISSUE THREAD

**Issue by JianWang2016** [Thie1e/cutpointr#53]
Hi Christian,

I wonder if oc_manual is used to specify a custom cutpoint.  I ran the following code to provide my own cutpoint instead of letting the function find the optimal cutpoint.  Not sure if oc_manual is used correctly but the output ignores my input. Please advise!

`
data(suicide)
opt_cut <- cutpointr(data = suicide, x = dsi, class = suicide, 
                     pos_class = 'yes', neg_class = 'no', 
                     direction = '>=', boot_stratify = TRUE,
                     oc_manual = 2.5)

`

Thanks much @Thie1e

**Comment by JianWang2016** [comment]
I found the answer as follows.

opt_cut <- cutpointr(data = suicide, x = dsi, class = suicide, 
                     pos_class = 'yes', neg_class = 'no', 
                     direction = '>=', boot_stratify = TRUE,
                     method = oc_manual, cutpoint = 2.5)

**Comment by Thie1e** [comment]
Hi Jian,

yes, your solution is correct. 

The first approach 'ignores' the `oc_manual` parameter, because is gets passed on to the metric function where it is then unused by `sum_sens_spec` when using the defaults.

Maybe we could issue a warning if parameters are supplied that are not being used by the metric function.
